// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbxwslnzifuxezozrwaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxieHdzbG56aWZ1eGV6b3pyd2FxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0OTc1MjgsImV4cCI6MjA2MDA3MzUyOH0.hdnNHLaVB1_A5IhF4A19BsiiQWJYJViDciup0ZuHQ4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);